<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE aeropuerto[
<!ELEMENT aeropuerto (nombre,vuelos,fechaPanel) >
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT vuelos (vuelo+) >
<!ELEMENT fechaPanel (#PCDATA) >
<!ELEMENT vuelo (diario?,origen,destino,salida,llegada) >
<!ATTLIST vuelo codigo ID #REQUIRED >
<!ATTLIST vuelo estado (C|E|R) "E" >
<!ELEMENT diario EMPTY >
<!ELEMENT origen (#PCDATA) >
<!ELEMENT destino (#PCDATA) >
<!ELEMENT salida (#PCDATA) >
<!ELEMENT llegada (#PCDATA) >
]>


<aeropuerto>
    <nombre>AGP</nombre>
    <vuelos>
        <vuelo codigo="v22" estado="R">
            <diario/>
            <origen>NY</origen>
            <destino>Chicago</destino>
            <salida>9:30</salida>
            <llegada>11:30</llegada>
        </vuelo>
        
        <vuelo codigo="v23" estado="C">
            <diario/>
            <origen>NY</origen>
            <destino>Miami</destino>
            <salida>9:30</salida>
            <llegada>11:30</llegada>
        </vuelo>
    </vuelos>
    <fechaPanel>13/2/23</fechaPanel>
</aeropuerto>

